src/guide/essentials/class-and-style.md
=> docs: fix typos

src/guide/components/async.md
=> docs: fix typo guide/components/async

src/guide/essentials/watchers.md
```
watchEffect(async () => {
const response = await fetch(url.value)
data.value = await response.json()
})
```
文档中例子应该是监听`url.value`的变化，错字：`question.value`
`question.value` --> `url.value`
=> docs(watchers): typo

src/guide/scaling-up/state-management.md
https://github.com/vuejs-translations/docs-zh-cn/issues/45 finished
考虑到以往的文档风格中，示例代码的非注释部分大多保留原文，因此把示例中**非注释**部分的代码改回了原文。
=> docs: update guide/scaling-up/state-management.md

src/guide/extras/animation.md, src/guide/extras/demos/AnimateWatcher.vue
1. src/guide/extras/animation.md:10
原文：
> However, there are many other ways of using animations on the web, even in a Vue application.
修改前：~~`但是在网页上制作动画的方式非常多，即使是在一个 Vue 应用中。`~~ 
修改后：`然而，在网页上制作动画的方式非常多，即使是在一个 Vue 应用中也是如此`。
结合上下文，此处 `However` 更应该翻成`然而`，且应在句尾添加`也是如此`让语句读起来更通顺。
2. src/guide/extras/animation.md:89
修改了某些地方，使译文更贴合原文含义，**PTAL**。
3. src/guide/extras/animation.md
line: 95、153、158、169
根据 `eslint `的`import/newline-after-import`规则，理应存在空行。
4. src/guide/extras/animation.md:127
原文：
> Move your mouse across this div...  
修改前：~~`移动鼠标穿过这个 div...`~~ 
修改后：`移动鼠标横着穿过这个 div...`。
其中 `across` 结合上下文及示例，翻为横着穿过。
5. src/guide/extras/animation.md:146
修改了某些地方，使译文更贴合原文含义，**PTAL**。
~~src/guide/extras/demos 下诸多与本章有关示例组件未翻译，添加翻译。~~
EDIT:
[示例及代码块里内容不应翻译。](https://github.com/vuejs-translations/docs-zh-cn/pul …
=> review: src/guide/extras/animation.md (#153)

src/guide/components/attrs.md
=> docs: undo translation of code blocks.

src/guide/essentials/template-syntax.md
根据 #167，将`缩写`更改为`简写`。
Closes #167
=> docs: correction shorthand.

src/guide/essentials/reactivity-fundamentals.md
误将英文原文 `original` 当作变量名。
> When you access `this.someObject` after assigning it, the value is a reactive proxy of the original `newObject` .
=> fix: variable name in reactivity-fundamentals.md

src/guide/components/attrs.md
改动标题的依据如下：
- 译文中的**标题**大部分用的是 `Attribute`，即首字母大写，单数形式，我认为应该将标题全都统一到这种形式
- 译文的**正文**中均使用 `attribute`，没有一致性问题
- 根据[翻译须知](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)，中文中夹杂的英文一律使用单数
改动正文中的那个句子的依据如下：
- 译文的语义错误，在原文中 `attribute` 和 `v-on event listener` 是并列关系，译文中这里翻译错了
=> fix(attrs.md): improve consistency

src/api/sfc-script-setup.md
使用纯类型声明来声明 prop 和 emits 的跳转是锚点是中文的，没有对齐英文，导致没法跳转
修改为英文锚点 typescript-only-features
无
=> docs(api): fix typescript-only-features anchor error.

src/api/reactivity-utilities.md
原文：
The above ref is **not** synced with `state.foo`, because the `ref()` receives a plain number value.
=> fix(api): translation error in reactivity-utilties.md

src/guide/typescript/options-api.md
中文文档勘误，`package.json` 中 `TypeScript` 声明文件对应字段应为 `types`，英文文档无误，应该是翻译时疏漏了
`type` -> `types`
=> fix(guide): type augmentation placement

src/guide/extras/web-components.md
English docs
hydrate 翻译问题
根据https://github.com/vuejs/docs-next-zh-cn/pull/786
应该将水合修改为“激活” (hydrate)
=> fix the hydrate translation

src/api/built-in-components.md
`KeepAlive`  case sensitive issue
=> fix KeepAlive tag name

src/api/ApiIndex.vue, src/api/api.data.ts
例如下图，当前中文api文档页面的显示和跳转都会出现问题：
这个PR修改了`api.data.ts`中的`headers`类型，并加上了对于`anchor`的特殊处理
=> fix(api): display bug

src/guide/essentials/reactivity-fundamentals.md, src/guide/essentials/template-syntax.md
英文原文为 "For other [falsy values](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) the attribute will be omitted."。`other falsy values` 翻译错误
原文 "Unlike in Vue 2, the original newObject is left intact and will not be made reactive:" 翻译错误
`other falsy values` 目前翻译为`假值`，应该翻译为 `其他假值`。
翻译为 "与 Vue 2 不同的是，这里原始的 `newObject` 不会变为响应式" 更为恰当
=> fix(template-syntax): change 'other falsy' translation

src/guide/introduction.md
原翻译：“Vue 2 中文文档已被迁移至”，其中“被”字多余，改为“Vue 2 中文文档已迁移至”更加清爽
删除“被”字
=> docs: remove redundant text

.vitepress/config.ts, src/api/application.md, src/api/sfc-spec.md, src/api/ssr.md, src/guide/best-practices/production-deployment.md, src/guide/built-ins/suspense.md, src/guide/quick-start.md, src/guide/scaling-up/routing.md, src/guide/scaling-up/sfc.md, src/guide/scaling-up/ssr.md, src/guide/scaling-up/state-management.md, src/guide/scaling-up/testing.md, src/guide/scaling-up/tooling.md, src/guide/typescript/overview.md
- Code of Conduct 翻译为“行为规范”
- 根据 https://github.com/vuejs/docs/commit/ebab2325755f3c6e29cf0b13b32f7d2936593cc6 更新生态系统菜单的翻译
- 对于 Vite、Vue CLI、Vue Router、Vuex、Vue Loader 等存在官方中文文档的生态库，替换链接至中文翻译
=> change ecosystem links to official translations

.vitepress/config.ts, .vitepress/theme/components/Home.vue
根据 Evan 在 https://github.com/vuejs-translations/docs-zh-cn/commit/36dda188b1e56778574ea765a9e8d6697e748963 所做的 review，将“快速开始”统一改为“快速上手”
=> docs: 快速上手

.vitepress/theme/styles/fonts.css, .vitepress/theme/styles/index.css, .vitepress/theme/styles/quotes.css
见 #530 
用指向本地文件的 `@font-face` 来把双引号强制使用中文字体渲染。
[效果预览](https://cn-vuejs-org-git-fork-justineo-fix-quotes-vuejs.vercel.app/guide/introduction.html#what-is-vue:~:text=%E7%81%B5%E6%B4%BB%E6%80%A7%E5%92%8C-,%E2%80%9C%E5%8F%AF%E4%BB%A5%E8%A2%AB%E9%80%90%E6%AD%A5%E9%9B%86%E6%88%90%E2%80%9D,-%E8%BF%99%E4%B8%AA%E7%89%B9%E7%82%B9%E3%80%82%E6%A0%B9%E6%8D%AE)
=> fix: force double quotes to be rendered with Chinese fonts

src/api/built-in-directives.md
Some titles of the md file have no anchor points. Do you want to add all of them.
api/built-in-component. md  api/ssr. md and so on.
=> fix: add title anchor

.vitepress/theme/styles/index.css, .vitepress/theme/styles/zh-cn.css
#571 I tried to solve this problem. You need to verify it.  ☺️
=> fix: try italic problem

src/api/utility-types.md
`v-bind:CSS` update `v-bind` CSS
sync vuejs/docs@72b203380bda37f83cbcf31805f969d67b7b0214
=> fix: typo v-bind CSS

src/guide/essentials/reactivity-fundamentals.md
The link of JavaScript Proxy is en-Us defaultly, so I replace it to adapt Chinese version
=> docs: replace mdn link to zh-CN version

src/guide/scaling-up/tooling.md
修复工具链-SFC 自定义块集成 - Vite示例链接404[链接](https://cn.vuejs.org/guide/scaling-up/tooling.html#sfc-custom-block-integrations)
=> fix(工具链-SFC 自定义块集成): 修复Vite示例链接404

vercel.json
When no extension is used, page is broken avec redirection: https://cn.vuejs.org/guide/introduction
Suggested by Evan You in private: vuejs.org uses Netlify with `cleanUrls` enabled.
Enabling it is solving the issue.
=> fix: Enable Vercel's cleanUrls options to avoid redirection issue

src/examples/src/cells/Cell/template.html, src/examples/src/todomvc/App/template.html, src/guide/extras/demos/SpreadSheetCell.vue
请确认：
@vnode-* hooks in templates are deprecated. Use the vue: prefix instead. For example, @vnode-mounted should be changed to @vue:mounted. @vnode-* hooks support will be removed in 3.4.
=> docs: change @vnode-mounted to @vue:mounted 

vercel.json
仅针对于 Vercel，Netlify 无此问题
访问 https://cn.vuejs.org/api/application.html 将会跳转到没有 `.html` 的地址，然后再跳转回来（最新 VitePress 已取消此行为 https://github.com/vuejs/vitepress/commit/ce8d139a8e70e4d0a8d06711c50119990b041078 ）
本 PR 之后：不再跳转。不论添加 html 或不添加，内容皆一致。
请确认：
=> fix: don't redirect to html-suffix url for vercel

.vitepress/config.ts, src/api/compile-time-flags.md
=> 翻译 /api/compile-time-flags.md

src/guide/components/events.md, src/guide/typescript/overview.md
请确认：
同步 [vuejs/docs](https://github.com/vuejs/docs/pull/2726)
=> docs: sync vue typescript overview docs

src/guide/extras/render-function.md, src/guide/quick-start.md, src/guide/scaling-up/tooling.md
请确认：
同步 https://github.com/vuejs/docs/pull/2734
=> docs: update Volar to Vue - Official

src/guide/essentials/class-and-style.md
请确认：
官方文档中的 `this` 应被完整翻译为 `指定接收的元素` (**this** refer to **define which element will receive this class**)
If your component has multiple root elements, you would need to define which element will receive this class. You can do **this** using the $attrs component property:
```diff
- 如果你的组件有多个根元素，你将需要指定哪个根元素来接收这个 class。你可以通过组件的 `$attrs` 属性来实现指定：
+ 如果你的组件有多个根元素，你将需要指定哪个根元素来接收这个 class。你可以通过组件的 `$attrs` 属性来指定接收的元素：
```
=> docs: fix translate mistake in /guide/essentials/class-and-style

src/guide/essentials/list.md
请确认：
翻译错误：
```diff
- 在外新包装一层 `<template>` 再在其上使用 `v-for` 可以解决这个问题 (这也更加明显易读)：
+ 在外先包装一层 `<template>` 再在其上使用 `v-for` 可以解决这个问题 (这也更加明显易读)：
```
=> typo: fix translate mistake in /guide/essentials/list

src/guide/best-practices/accessibility.md
请确认：
`Chrome DevTools` should be translated to `Chrome 开发者工具`
=> fix: wrong translate of Chrome DevTools

src/api/custom-elements.md
=> docs: translate custom-elements.md

src/api/composition-api-helpers.md
请确认：
useModel 缺失返回类型
sync commit https://github.com/vuejs/docs/commit/e20eb77a4ef3e0c32c081be7190cb861400c37ff
=> docs: missed return value type for useModel()

src/developers/components/DeveloperLanding.vue, src/developers/partnerConfig.js
=> docs: translate developer articles

src/api/options-lifecycle.md, src/guide/extras/render-function.md
=> docs: translate todos

src/api/application.md
The current documentation states that compilerOptions.comments controls  "whether to remove HTML comments", which may cause confusion. 
In practice:
- Default (false): comments are removed in production builds.
- True: comments are retained even in production.
This commit updates the description to clarify that the option  actually controls whether comments are preserved, not removed.
请确认：
=> Clarify compilerOptions.comments description in docs

src/api/composition-api-helpers.md
=> docs: remove unnecessary characters
