vuejs-translations/docs-zh-cn

src/about/translation.md
Fixed a typo in the counter-example.
Replaced `这是一个*斜体*尝试 ` with `这是一个_斜体_尝试 `
=> docs: fixed a typo

.vitepress/config.ts, .vitepress/headerMdPlugin.ts, .vitepress/theme/components/NewsLetter.vue, .vitepress/theme/components/PreferenceSwitch.vue
- Sync the update line-by-line.
- Some tiny translation suggestions.
Thanks.
=> chore: sync site config line-by-line

src/guide/best-practices/accessibility.md
#25 与此同时加入了 MDN 的链接
英文版我也发了 PR
https://github.com/vuejs/docs/pull/1455
=> Revert the translation of landmark and link to MDN

src/guide/built-ins/keep-alive-demos/SwitchComponent.vue
内置组件 KeepAlive 章节中的第一个例子没按照预期工作，切换组件后状态没有被重置
微调了一下代码逻辑
英文版文档中该问题已经被修复
=> docs: fix KeepAlive example

README.md, package.json
=> docs: Add node version description

src/guide/typescript/composition-api.md, src/guide/typescript/options-api.md
=> typed -> 标注类型 from 类型化

src/guide/scaling-up/tooling.md
=> docs(tooling): review src/guide/scaling-up/tooling.md

src/guide/extras/web-components.md
=> docs: correct import file .ext

src/guide/essentials/lifecycle.md
=> docs: review src/guide/essentials/lifecycle.md

src/guide/essentials/conditional.md
=> docs: review src/guide/essentials/conditional.md 

src/guide/best-practices/performance.md
review src/guide/best-practices/performance.md
#76
=> docs(performance: review src/guide/best-practices/performance.md

src/guide/quick-start.md
Add scaffolding tool features support
=> docs: update quick-start.md

src/guide/essentials/watchers.md
[src](https://github.com/vuejs/docs/blame/main/src/guide/essentials/watchers.md#L199)
=> 代码部分注释中变量名的错别字

src/guide/components/events.md
- 修改部分翻译内容
- 按照`wiki`中的术语翻译约定，进行了修改
- 修改了标点符号
=> docs: review src/guide/components/events.md

.github/workflows/autosync.yml
Commitor: initdc
auto sync repo
add action
https://github.com/marketplace/actions/github-forks-sync-action
You may need update the branch name at first(#121),
then exec this action
remember update `target_repository`
setup `GH_PERSONAL_ACCESS_TOKEN`
=> ci(autosync): add action for pull upstream

src/guide/best-practices/accessibility.md, src/guide/built-ins/teleport.md, src/guide/built-ins/transition-demos/Basic.vue, src/guide/built-ins/transition-demos/BetweenElements.vue, src/guide/built-ins/transition-demos/CssAnimation.vue, src/guide/built-ins/transition-demos/JsHooks.vue, src/guide/built-ins/transition-demos/NestedTransitions.vue, src/guide/built-ins/transition-demos/SlideFade.vue, src/guide/built-ins/transition.md, src/guide/components/attrs.md, src/guide/components/props.md, src/guide/essentials/class-and-style.md, src/guide/essentials/component-basics.md, src/guide/essentials/forms.md, src/guide/essentials/list.md, src/guide/essentials/reactivity-fundamentals.md, src/guide/essentials/template-refs.md, src/guide/essentials/template-syntax.md, src/guide/essentials/watchers.md, src/guide/reusability/custom-directives.md
根据 #35，代码块部分不应翻译。
正在修复其他章节的问题~
=> docs: undo translation of code blocks.

src/guide/built-ins/transition-demos/ListStagger.vue, src/guide/built-ins/transition-group.md
props未按约定使用单数
过滤列表的值与英文文档不一致。且中文文档中，下方的”[在 Playground 中查看完整示例](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgY29tcHV0ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgZ3NhcCBmcm9tICdnc2FwJ1xuXG5jb25zdCBsaXN0ID0gW1xuICB7IG1zZzogJ0JydWNlIExlZScgfSxcbiAgeyBtc2c6ICdKYWNraWUgQ2hhbicgfSxcbiAgeyBtc2c6ICdDaHVjayBOb3JyaXMnIH0sXG4gIHsgbXNnOiAnSmV0IExpJyB9LFxuICB7IG1zZzogJ0t1bmcgRnVyeScgfVxuXVxuXG5jb25zdCBxdWVyeSA9IHJlZignJylcblxuY29uc3QgY29tcHV0ZWRMaXN0ID0gY29tcHV0ZWQoKCkgPT4ge1xuICByZXR1cm4gbGlzdC5maWx0ZXIoKGl0ZW0pID0+IGl0ZW0ubXNnLnRvTG93ZXJDYXNlKCkuaW5jbHVkZXMocXVlcnkudmFsdWUpKVxufSlcblxuZnVuY3Rpb24gb25CZWZvcmVFbnRlcihlbCkge1xuICBlbC5zdHlsZS5vcGFjaXR5ID0gMFxuICBlbC5zdHlsZS5oZWlnaHQgPSAwXG59XG5cbmZ1bmN0aW9uIG9uRW50ZXIoZWwsIGRvbmUpIHtcbiAgZ3NhcC50byhlbCwge1xuICAgIG9wYWNpdHk6IDEsXG4gIC …
=> review: src/guide/built-ins/transition-group.md

src/guide/built-ins/suspense.md
=> fix: suspensible 未被正确加粗问题

src/guide/essentials/forms.md
=> fix: forms.md

src/guide/essentials/reactivity-fundamentals.md
=> fixed: guide/essentials/reactivity-fundamentals.md

src/guide/reusability/custom-directives.md
=> fix the word

.github/contributing/writing-guide.md, src/api/built-in-special-elements.md, src/api/reactivity-advanced.md, src/api/sfc-spec.md, src/guide/essentials/component-basics.md, src/guide/essentials/event-handling.md, src/guide/essentials/reactivity-fundamentals.md, src/guide/extras/web-components.md, src/guide/scaling-up/ssr.md, src/sponsor/index.md, src/tutorial/src/step-8/App/template.html, src/tutorial/src/step-8/_hint/App/template.html, src/tutorial/src/step-8/description.md
=> Sync upstream

src/guide/essentials/conditional.md, src/guide/scaling-up/routing.md
修正了两处的VueSchoolLink：
1. src/guide/essentials/conditional.md
翻译VueSchoolLink的title内容
2. src/guide/scaling-up/routing.md
翻译VueSchoolLink的title内容，以及删除里面的文字，因为默认就有正确的翻译文字
=> review: src/guide/essentials/conditional.md and src/guide/scaling-up/routing.md

src/guide/components/slots.md
=> fixed: slots.md

src/guide/components/events.md
=> fix: fixed link in src/guide/components/events.md

src/guide/components/props.md
=> docs(props): review src/guide/components/props.md

.vitepress/config.ts
官网首页导航->生态系统下拉菜单配置错误,多了一个视频教程的错误配置
删除多余配置
=> fix(config.ts): remove redundant modules from the navigation-ecosystem

src/guide/extras/reactivity-in-depth.md
=> fix: remove unnecessary punctuation

src/guide/extras/reactivity-transform.md
=> fix(reactivity-transform.md): semantically unreasonable

src/guide/extras/reactivity-transform.md
=> docs(cn): fix typo

src/api/sfc-script-setup.md
https://github.com/vuejs-translations/docs-zh-cn/actions/runs/2113828817
Remove dead links
=> fix: remove dead link for deploy to gitee

src/guide/extras/composition-api-faq.md
=> docs(composition-api-faq): fix incorrect word

src/guide/extras/composition-api-faq.md
=> docs(composition-api-faq): fix typo

src/api/sfc-spec.md
=> fix: api/sfc-spec.md typo

src/api/application.md
=> docs(api): plugin typo

src/guide/essentials/component-basics.md
Close #281 
翻译错误
旧翻译：如果模板时写在 DOM 中
新翻译：如果刚才的模板是写在 DOM 中
=> docs: component-basics.md

src/guide/built-ins/keep-alive.md
spelling error
`onDectivated` -> `onDeactivated`
=> fix(keep-alive): fix spelling error

src/api/built-in-components.md
我又来啦。这次我主要翻译了 src/api/built-in-components.md。PTAL~ 辛苦大家啦~
Closes #293
=> docs(cn): api/built-in-components.md translation completed

src/api/options-rendering.md
对比英文原文修改了一些语句，使读起来更通顺。
closes #306
=> docs(api): review options-rendering.md

package.json
=> update: @vue/theme

src/api/sfc-spec.md
close [#296](https://github.com/vuejs-translations/docs-zh-cn/issues/296)
=> review: api/sfc-spec.md

src/api/application.md
`相关内容` => `参考` 并调整了部分语序
close #266
有什么更好的建议，欢迎大家参与讨论
=> docs(api): review src/api/application.md

src/api/composition-api-dependency-injection.md
=> docs(api): review src/api/composition-api-depenency-injection.md and index.md

src/api/built-in-components.md
https://github.com/vuejs-translations/docs-zh-cn/pull/297#issuecomment-1109191817
=> Review api/built-in-components

src/api/application.md, src/api/built-in-components.md, src/api/built-in-special-attributes.md, src/api/built-in-special-elements.md, src/api/composition-api-dependency-injection.md, src/api/composition-api-lifecycle.md, src/api/composition-api-setup.md, src/api/general.md, src/api/options-composition.md, src/api/options-lifecycle.md, src/api/options-rendering.md, src/api/reactivity-core.md, src/api/reactivity-utilities.md, src/api/render-function.md, src/api/sfc-css-features.md, src/api/sfc-spec.md, src/api/ssr.md
通过 zhlint 将所有已经校对完毕的 API 文档进行了格式化
=> fix the format in all reviewed api/**/*.md with zhlint

src/guide/essentials/list.md
=> docs(guide): fix guide/essentials/list.md

src/guide/scaling-up/tooling.md
[link](https://vue-loader.vuejs.org/custom-blocks.html#custom-blocks) is invalid
=> Fixed broken CustomBlocks link

src/guide/scaling-up/ssr.md
[link](https://github.com/vitejs/vite/tree/main/packages/playground/ssr-vue) is invalid
=> Fixed broken demo link

package.json, pnpm-lock.yaml
Removed `patch-vue-directive-ssr` which is not needed anymore
=> removed legacy deps

src/tutorial/TutorialRepl.vue, src/tutorial/index.md, src/tutorial/src/step-1/description.md
=> docs(zh): translate tutorial step-1

src/guide/quick-start.md
=> docs(guide/quick-start.): fix untranslated

src/guide/built-ins/suspense.md
=> docs(Suspense): fix markdown style

src/tutorial/src/step-3/App/template.html, src/tutorial/src/step-3/description.md
=> docs(tutorial): translation src/tutorial/src/step-3 completed

src/guide/essentials/event-handling.md
=> fix: fix typos

src/guide/essentials/watchers.md
=> chore: improve translation

src/guide/components/events.md
我不确定我这个改动是否可以，但是原翻译的“发射”很怪异，而且根本不对应英文原文
=> feat: translation improvement

src/tutorial/src/step-2/description.md
=> docs(tutorial/src/step-2): translate

src/tutorial/src/step-1/description.md, src/tutorial/src/step-2/description.md
Header anchor should be slugified.
=> fix: fix anchor

.vitepress/theme/components/PreferenceSwitch.vue
- SFC -> 单文件组件
- Some ARIA attributes
=> Translated preference switch

src/examples/src/conditionals-and-loops/description.txt, src/examples/src/form-bindings/App/template.html, src/examples/src/form-bindings/description.txt
- conditionals and loops
- form bindings
=> Translated all the rest basic examples

src/tutorial/src/step-7/App/composition.js, src/tutorial/src/step-7/App/options.js, src/tutorial/src/step-7/_hint/App/composition.js, src/tutorial/src/step-7/_hint/App/options.js, src/tutorial/src/step-7/description.md
close [405](https://github.com/vuejs-translations/docs-zh-cn/issues/405)
=> doc(tutorial): finish the step-7 translation

src/api/sfc-script-setup.md
=> review: sfc-script-setup.md

src/guide/components/attrs.md
=> docs(guide): translate untranslated comments

src/tutorial/src/step-8/description.md
=> docs(tutorial): translate src/tutorial/src/step-8

src/tutorial/src/step-13/description.md
=> docs(tutorial): translate src/tutorial/src/step-13

src/examples/src/cells/store.js
=> Translated 7guis examples

README.md
=> Update repo status on README.md

src/translations/index.md
=> 翻译了 translations 页面

src/guide/extras/reactivity-in-depth.md
=> docs(guide): remove duplicate word

src/guide/built-ins/transition.md
根据[术语翻译约定](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)，listener是「监听器」，observer和watcher是「侦听器」。
更正event listener的翻译。
=> 更正 event listener 的翻译

src/guide/components/events.md
=> Update the Component Events section

src/api/general.md, src/guide/typescript/overview.md
Note on webpack Treeshaking未翻译。
翻译该节。
=> Translate the note on webpack Treeshaking

src/api/application.md
=> perfect: Add missing fields

README.md
There are untranslated parts of readme.
Translate it.
=> docs: Translate untranslated parts

src/api/ApiIndex.vue
=> docs(zh): fix api ahchor

src/api/sfc-script-setup.md, src/guide/built-ins/transition.md, src/guide/extras/composition-api-faq.md
https://github.com/vuejs-translations/docs-zh-cn/compare/ba5f0fb177c70f597b80d31420589a9d48383440...233c074ff8a13ca99711f0369313b6855252d929
部分文件已在 #451 和 #454 中得到处理。
=> Sync #233c074

src/guide/introduction.md
sync with https://github.com/vuejs/docs/commit/cc15d625fdec77dbb4f09854795fbc70babfdac9
=> feat: added a link to MDN JS guide

README.md
为首页添加了贡献者列表 PNG
```
<p align="center">
</p>
```
<p align="center">
</p>
=> chore(readme): add contributors list image

src/style-guide/PLEADE_DO_NOT_TRANSLATE.md
Fix #475
Another ref: https://github.com/vuejs-translations/docs-zh-cn/pull/237#issuecomment-1148418220
=> Create PLEADE_DO_NOT_TRANSLATE.md for style-guide

src/guide/extras/web-components.md
fix: `defineCustomElment`  -> `defineCustomElement`
=> fix: fix spell error

src/api/built-in-directives.md
=> v-show 中过渡的渡写错了

src/guide/components/props.md
just a trivial edit to make meaning more clear
=> fix typo in props.md

src/guide/reusability/composables.md
病句: "组合式 API 的一部分灵感正来自于 React hooks 的组合式函数也的确在逻辑组合能力上与 React hooks 相近。"
修改后: "组合式 API 的一部分灵感正来自于 React hooks, Vue 的组合式函数也的确在逻辑组合能力上与 React hooks 相近。"
None
=> Fix composables.md 中病句

src/about/faq.md
https://github.com/vuejs/docs/issues/1908
Fix the typo.
=> Editorial fix

.github/ISSUE_TEMPLATE/bug_report.yaml
增加 isssue template
[预览地址](https://github.com/wxsms/vuejs-docs-zh-cn/issues/new?assignees=&labels=&template=bug_report.yaml)
=> chore: add issue template

src/guide/best-practices/performance.md
No Chinese translation.
Add Chinese translation.
=> Translate Choosing the Right Architecture

src/guide/essentials/list.md
https://github.com/vuejs/v2.cn.vuejs.org/issues/1221
=> update the translation of range

src/guide/scaling-up/testing.md
Refer to the source's official website: https://cn.vitest.dev/config/#globals
=> change "global" to "globals"

src/guide/extras/reactivity-transform.md, src/guide/typescript/composition-api.md
vuejs/docs@b392b068fb893e3ac6079710fe34decbde7a3be3
=> Sync commit b392b068fb893e3ac6079710fe34decbde7a3be3

src/guide/quick-start.md
sync with https://github.com/vuejs/docs/commit/6400d164f4b02d52080707e32e9a4152c7960ba5
=> feat: sync commit 6400d164f4b02d52080707e32e9a4152c7960ba5

src/guide/best-practices/accessibility.md
=> fix: 无障碍访问 Landmark 提示

src/guide/scaling-up/ssr.md
=> fix: colon

.vitepress/inlined-scripts/restorePreference.js, .vitepress/theme/components/Banner.vue, .vitepress/theme/components/Home.vue, .vitepress/theme/index.ts, src/guide/quick-start.md, src/guide/typescript/composition-api.md
https://github.com/vuejs/docs/compare/2019035796a19986451276b7fbe3d8bc492a8964...b2d3a52f63e293168037afdaaf4ef3af37373899
already done before:
* https://github.com/vuejs-translations/docs-zh-cn/pull/539
* https://github.com/vuejs-translations/docs-zh-cn/pull/537
=> Sync #b2d3a52

src/guide/built-ins/transition.md
=> fix：CSS 的 animation 部分，transition单词拼写错误

src/tutorial/src/step-9/description.md
ref: [commit](https://github.com/vuejs-translations/docs-zh-cn/commit/047377c141524416fda63483722cb7943a0871f1) from Evan You
=> fix: change 模版 to 模板

package.json, pnpm-lock.yaml
chore:update @vue/repl version  vuejs/docs@12d36c981bc8d162917be7b64a16fcd365307795
=> chore:update @vue/repl version

src/guide/scaling-up/tooling.md, src/guide/typescript/overview.md
update `vue-tsc` link  vuejs/docs@c8177eab6ceac0af195f044de112c8309d4f821d
=> fix:update vue-tsc link

src/about/faq.md
=> fix: update faq

src/guide/quick-start.md
=> fix: Markdown 语法问题

src/guide/typescript/overview.md
Reverts vuejs-translations/docs-zh-cn#575
=> Revert "chore: format overview.md by codeflow (#572)"

.vitepress/config.ts
#582 
- fixed wrong i18n keys
- added more type informations
=> Update vitepress config (fix #582)

src/guide/essentials/forms.md
Inappropriate use of colons at the end of sentences
Using semicolon replace colon
=> fix: replace inappropriate punctuation

src/guide/best-practices/accessibility.md, src/guide/scaling-up/tooling.md
fix the bug of repeated characters.
file path:
- `src/guide/best-practices/accessibility.md`
- `src/guide/scaling-up/tooling.md`
=> fix: the bug of repeated characters.

src/guide/components/provide-inject.md
string extra
* \src\guide\components\provide-inject.md
=> string Extra

.vitepress/config.ts, src/guide/scaling-up/ssr.md, src/guide/scaling-up/state-management.md, src/style-guide/rules-strongly-recommended.md
the chinese version of pinia docs have be released, so I update it's link
=> docs(zh): update pinia docs link

src/ecosystem/themes/ThemeListItem.vue, src/ecosystem/themes/ThemePage.vue, src/ecosystem/themes/ThemeProduct.vue, src/ecosystem/themes/themes.json
=> themes page translation

src/guide/introduction.md, src/guide/quick-start.md
最近想重读一遍 Vue3 文档，在此过程中，尝试给一些翻译润润色
=> docs: polish some translations

src/guide/essentials/watchers.md, src/guide/extras/render-function.md
=> docs(cn): update translation

src/guide/essentials/computed.md, src/guide/essentials/conditional.md, src/guide/essentials/list.md, src/guide/extras/composition-api-faq.md, src/guide/extras/web-components.md
https://github.com/vuejs-translations/docs-zh-cn/issues/601 更新链接
Linked from <a href="https://cn.vuejs.org/about/faq.html" rel="nofollow">https://cn.vuejs.org/about/faq.html</a>~~
Linked from <a href="https://cn.vuejs.org/guide/essentials/computed.html" rel="nofollow">https://cn.vuejs.org/guide/essentials/computed.html</a>
Linked from <a href="https://cn.vuejs.org/guide/extras/composition-api-faq.html" rel="nofollow">https://cn.vuejs.org/guide/extras/composition-api-faq.html</a>
Linked from <a href="https://cn.vuejs.org/guide/essentials/application.html" rel="nofollow">https://cn.vuejs.org/guide/essentials/application.html</a>~~
Linked from <a href="https://cn.vuejs.org/guide/scaling-up/ssr.html" rel="nofollow">https://cn.vuejs.org/guide/scaling-up/ssr.html</a>~~
Linked from <a …
=> docs(cn): update broken links

src/guide/essentials/watchers.md, src/guide/scaling-up/testing.md
https://github.com/vuejs/docs/compare/5bb7094e...dceccbb2
=> Sync #dceccbb2

src/guide/scaling-up/tooling.md
https://github.com/vuejs/docs/compare/8bb74808...49545c20
=> Sync #49545c20

src/guide/quick-start.md
=> fix a expression error

src/guide/essentials/template-syntax.md
=> fix an incomplete expression

.vitepress/config.ts, src/ecosystem/newsletters.md
note: L13 由于原文所提链接指向相应仓库。此处应该需要引导回英文仓库。因此做了些许修改。
=> translate todo in newsletters.md

src/guide/essentials/event-handling.md
Fixes: vuejs/docs#2217
We have update the translation of this section, so update the hash.
=> fix: update the link to an example

src/guide/extras/composition-api-faq.md
=> fix: composition-api-faq.md

.vitepress/theme/components/SiteMap.vue
修复https://github.com/vuejs-translations/docs-zh-cn/issues/653
=> fix(sitemap): bug error

LICENSE, README.md, package.json
relate issue https://github.com/vitejs/docs-cn/issues/703
=> chore: change license

.vitepress/config.ts
- 目前 algolia 搜索功能没有翻译
- 根据 TODO 更新 `ariaAnnouner` 配置信息
|before|after|
|:--:|:--:|
|![image](https://user-images.githubusercontent.com/54026110/224055039-f7231eb0-2f92-4433-8cee-afb410e9cd96.png)|![image](https://user-images.githubusercontent.com/54026110/224055101-3c3b3cc0-7226-4222-ba7e-5acb85184a96.png)|
https://github.com/vuejs/theme/issues/75
=> docs: algolia search translate

src/guide/essentials/event-handling.md
第一处的粗体没有渲染出来，第二处的斜体在中文排版时会出现字体重叠
第一处按照英文原文进行修改（删除粗体），第二处在前后加上了一个空格
我在将仓库克隆到本地后运行，已经正确的按照 README 安装相关的包，但是打开预览网页时一片空白，控制台显示报错信息 `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`
我尝试了一下英文文档的预览，没有问题，请问我应该怎样预览呢😀
=> 修改 事件处理 章节的一些标点符号问题 

src/about/coc.md
用户从英文版 coc 页面切换语言至中文版时，页面显示 404。添加一个页面可以改善这种情况。
另：貌似现在是部署在 vercel，那么 coc 页面可以加回来了？
=> add coc page

.vitepress/config.ts, .vitepress/theme/components/Home.vue, .vitepress/theme/components/PreferenceSwitch.vue, .vitepress/theme/components/VueMasteryModal.vue, package.json, pnpm-lock.yaml, src/examples/ExampleRepl.vue, src/examples/index.md
https://github.com/vuejs/docs/compare/36f2cff5...127093f6
=> Sync #127093f6

.vitepress/config.ts, .vitepress/inlined-scripts/restorePreference.js, .vitepress/textAdMdPlugin.ts, .vitepress/theme/components/Banner.vue, .vitepress/theme/components/TextAd.vue, .vitepress/theme/index.ts, package.json, pnpm-lock.yaml, src/about/team/members-core.json, src/api/ApiIndex.vue, src/api/render-function.md, src/guide/essentials/application.md, src/guide/extras/composition-api-faq.md, src/guide/extras/render-function.md, src/guide/typescript/composition-api.md, src/guide/typescript/options-api.md, src/partners/partners.json
https://github.com/vuejs/docs/compare/ecff8104...3cb76a49
=> Sync #3cb76a49

src/guide/extras/reactivity-in-depth.md
=> fix: remove excess characters

README.md
请确认：
将“如何参与贡献”稍微提到 readme 中较前的位置，并且添加了一行关于不接受某些类型的贡献的描述。
=> docs: update readme, raise how to contribute

src/guide/essentials/template-syntax.md, src/guide/introduction.md, src/guide/quick-start.md, src/guide/reusability/composables.md
https://github.com/vuejs/docs/compare/5b045c22...f618a3a5
=> Sync #f618a3a5

.vitepress/config.ts, src/about/community-guide.md
=> fix: fix links to coc

src/api/application.md
=> docs: translate api application

src/guide/essentials/component-basics.md
=> use the more understandable translation of `accessibility` (#734)

src/guide/reusability/composables.md
=> feat: translate todo in composables.md

src/guide/essentials/reactivity-fundamentals.md
=> feat: translate todo in reactivity-fundamentals.md

src/guide/essentials/template-syntax.md
请确认：
- [ x ] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [ x ] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)
替换XSS漏洞的百科链接为维基百科中文版
=> 替换XSS漏洞的百科链接为维基百科中文版

src/api/built-in-directives.md
=> docs: Update built-in-directives.md 一个小问题

src/guide/essentials/reactivity-fundamentals.md
请确认：
修复锚点，位置： 响应式基础 -> ref() -> 注意事项
=> fix: fix caveat-when-unwrapping-in-templates link

src/guide/essentials/reactivity-fundamentals.md
请确认：
> To access refs in a component's template, 
翻译从 `要访问组件模板中的 ref，` 改为 `要在组件模板中访问 ref，`
close #757
=> Edit translation of 'To access refs in a component's template, '

package.json, pnpm-lock.yaml, src/about/team/members-partner.json, src/api/reactivity-core.md, src/guide/quick-start.md, src/guide/scaling-up/tooling.md
https://github.com/vuejs/docs/compare/99bda99f...6ce6bc4f
=> Sync #6ce6bc4f

.vitepress/theme/components/PreferenceTooltip.vue
=> translate tooltip

.vitepress/config.ts
=> refactor: update license on website

src/guide/best-practices/security.md
请确认：
- [√] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [√] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)
=> docs(typo): Update security.md

src/guide/essentials/watchers.md
=> style: remove redundant spaces

src/guide/typescript/overview.md
=> docs: typo

src/guide/components/events.md
=> Update: Translated the events-props of the event

src/about/faq.md
=> fix: Missing links to zh documents

src/api/built-in-directives.md
=> translate TODO in built-in-directives.md

src/api/reactivity-core.md, src/guide/best-practices/performance.md
=> translate `computed stability`

src/guide/components/v-model.md
=> docs(cn): translate todo

src/api/sfc-script-setup.md
请确认：
https://github.com/vuejs-translations/docs-zh-cn/pull/815#discussion_r1454885779
=> Update sfc-script-setup.md for a typo

src/guide/extras/render-function.md
请确认：
翻译 JSX 类型推断一段内容，设置 ts + jsx 类型配置
=> docs: translate jsx-type-inference

src/guide/essentials/template-syntax.md
请确认：
docs: translate Same-name Shorthand
=> docs: translate Same-name Shorthand

src/error-reference/index.md
请确认：
更新翻译 src/error-reference/index.md
=> Update: translate src/error-reference/index.md

src/about/community-guide.md
=> fix: Correct a translation error

src/guide/typescript/overview.md
请确认：
更新翻译：[src/guide/typescript/overview.md](https://github.com/vuejs-translations/docs-zh-cn/blob/a3a47ff723b58d8fa3c89e6ba15457ee5dee8e40/src/guide/typescript/overview.md?plain=1#L51)
=> Update translate overview.md

src/api/reactivity-core.md
=> translate todo in reactivity-core.md

src/guide/essentials/template-syntax.md
=> translate comments in template-syntax.md

src/guide/extras/reactivity-transform.md
请确认：
更新翻译：[src/guide/extras/reactivity-transform.md](https://github.com/vuejs-translations/docs-zh-cn/blob/a3a47ff723b58d8fa3c89e6ba15457ee5dee8e40/src/guide/extras/reactivity-transform.md?plain=1#L11)
=> Update translate reactivity-transform.md

src/guide/components/v-model.md
请确认：
Update translate src/guide/components/v-model.md
=> docs: Update translate src/guide/components/v-model.md

src/tutorial/src/step-1/description.md
=> docs: Update translate src/tutorial/src/step-1/description.md

src/guide/essentials/watchers.md
=> docs: Update translate src/guide/essentials/watchers.md

src/guide/essentials/watchers.md
=> Update: translate src/guide/essentials/watchers.md

src/guide/components/v-model.md
=> translate todos in v-model.md

src/guide/extras/composition-api-faq.md
=> move gist code into this repo as assets (close #712)

pnpm-lock.yaml, src/api/sfc-script-setup.md, src/guide/components/props.md, src/guide/components/v-model.md, src/guide/essentials/watchers.md, src/guide/extras/reactivity-in-depth.md, src/guide/scaling-up/tooling.md
https://github.com/vuejs/docs/compare/d7a77fe8...d3e37ab8
=> Sync #d3e37ab8

src/tutorial/src/step-7/App/template.html, src/tutorial/src/step-8/App/template.html, src/tutorial/src/step-8/_hint/App/template.html
vuejs/docs#2712
add verify to avoid empty content for newTodo
请确认：
=> docs: sync tutorial/step-7&8 change

src/guide/built-ins/transition.md, src/guide/quick-start.md
https://github.com/vuejs/docs/compare/d3e37ab8...ee2c10b7
部分内容在 #865 和 #866 中覆盖
=> Sync #ee2c10b7

src/guide/extras/render-function.md, src/guide/scaling-up/tooling.md, src/guide/typescript/overview.md
=> fix: fix zhlint errors

src/guide/built-ins/transition.md
请确认：
[/src/guide/built-ins/transition.md]
some sentences need punctuation adjustments at the end.
=> fix: adjust punctuation in /src/guide/built-ins/transition.md.

src/guide/extras/reactivity-in-depth.md
请确认：
- [ x] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [x ] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)
produce 需要从 immer 具名导入
对齐[英文文档](https://vuejs.org/guide/extras/reactivity-in-depth.html#immutable-data)
=> docs: correct immer produce import in reactivity-in-depth.md

src/guide/built-ins/transition.md
请确认：
translate:  Transitions with the Key Attribute
=> Update: translate src/guide/built-ins/transition.md

src/glossary/index.md
请确认：
Missing spaces between words
=> fix(docs): missing spaces between words

src/guide/best-practices/performance.md
=> docs: translate remark in /guide/best-practices/performance

src/tutorial/src/step-11/App/composition.js, src/tutorial/src/step-11/App/options.js
请确认：
**注: `src/tutorial/src/step-11/App/composition.js` 原文内容错误，应为 `register child component`，[错误已在原仓库修改](https://github.com/vuejs/docs/pull/2837)，等待合并并同步，但本PR不做修改**
=> docs: translate remark in tutorial 11

.vitepress/headerMdPlugin.ts, src/api/reactivity-core.md, src/guide/quick-start.md
https://github.com/vuejs/docs/compare/50f3f20a...35e8da8b
=> Sync #35e8da8b

src/api/sfc-css-features.md
=> fix: change commas to full width

src/guide/components/props.md
=> fix: update props.md

src/api/sfc-script-setup.md
=> fix(sfc-script-setup): change commas to full width

src/api/render-function.md
请确认：
change type of `withModifiers` param
`string[]` -> `ModifierGuardsKeys[]`
=> docs(withModifiers): change type of withModifiers param

src/guide/components/props.md
请确认：
修改了注释的描述，原文中 空的字符串 可以理解为 ''，这里修改为 String 类型或 null
=> docs(props): update comment content

src/guide/components/v-model.md
请确认：
Compared to the source document, the example is missing code
=> fix: fix missing code in defineModel example

src/guide/components/v-model.md
请确认：
add missing text
`v-model 参数` -> `v-model 的参数`
=> docs(v-model): add missing text

src/guide/components/props.md
=> docs(props): update the translation of `nullable`

.vitepress/theme/components/Home.vue
请确认：
- [ x ] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [ x ] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)
Fix link
`https://v2.vuejs.org/eol/` -> `https://v2.cn.vuejs.org/eol/`
=> docs: fix vue2 Security Update jump link

.vitepress/theme/components/SecurityUpdateBtn.vue
请确认：
- [ x ] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [ x ] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)
`Get Security Updates for Vue 2` -> `获取针对 Vue 2 的安全更新`
=> fix(SecurityUpdateBtn): translate

src/guide/typescript/composition-api.md
=> docs: translate guide/typescript/composition-api.md

src/api/composition-api-helpers.md
=> fix: make zhlint happy again

.github/workflows/ci.yml
=> fix: ci.yml branch name

src/guide/components/props.md
=> docs(props): correct a wrong sentence

src/guide/components/props.md
=> docs: add space

src/guide/typescript/composition-api.md
请确认：
文档给的例子中，组件名称拼写错误。在英文文档是正确的。
=> corrected spelling errors

src/guide/built-ins/suspense.md
=> chore: replace '槽' with ‘插槽’

src/guide/components/provide-inject.md
请确认：
修改示例代码格式，删除多余分号，与英文文档保持一致
=> docs(provide-inject): correct code formatting.

src/api/built-in-special-attributes.md
…/built-in-special-attributes.
请确认：
修改 `内置的特殊 Attributes`  中 `ref` 位置获取dom的方法，使用 `useTemplateRef` 替换 `ref`。与英文文档保持一致。
=> fix(Built-in Special Attributes): correct the methods used in src/api/built-in-special-attributes

src/tutorial/src/step-7/description.md
=> fix typo 的 -> 地

src/guide/essentials/reactivity-fundamentals.md
=> docs: 深入响应式原理->深入响应式系统 与侧边栏保持一致

src/guide/essentials/computed.md
请确认：
同步英文文档中关于 `computed` getter 参数在选项式中的位置
请查看：[docs(computed): correct parameter positions in the computed example #3244](https://github.com/vuejs/docs/pull/3244)
=> docs(computed): sync English doc

src/about/privacy.md
请确认：
- [ x ] 我已经阅读过项目的 [wiki](https://github.com/vuejs-translations/docs-zh-cn/wiki) 了解相关注意事项。
- [ x ] 我对翻译内容的改动不包含基于英文原版的扩展、删减或演绎 (如有，请移步至[英文文档仓库](https://github.com/vuejs/docs)讨论，相关结论会被定期从英文版同步)
=> docs(privacy): fix misplaced bold formatting in text

src/api/custom-elements.md
=> Fix link in defineCustomElement() documentation
